//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using HMS.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int Bill_Id { get; set; }
        public decimal PaymentAmount { get; set; }
        public int UserId { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual User User { get; set; }
    }
}
