//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Bill_Id { get; set; }
        public System.DateTime BillDate { get; set; }
        public int BookingId { get; set; }
        public decimal TotalRoomCharge { get; set; }
        public decimal TotalServiceCharge { get; set; }
        public decimal TotalCharge { get; set; }
        public decimal TotalPayment { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Booking Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
