//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HotelManagementSystemEntities : DbContext
    {
        public HotelManagementSystemEntities()
            : base("name=HotelManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingStatu> BookingStatus { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomStatu> RoomStatus { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_ActiveUserID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_ActiveUserID");
        }
    
        public virtual ObjectResult<string> SP_ActiveUserName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_ActiveUserName");
        }
    
        public virtual ObjectResult<SP_RoomTypesTotal_Result> SP_RoomTypesTotal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RoomTypesTotal_Result>("SP_RoomTypesTotal");
        }
    
        public virtual ObjectResult<SP_RoomTypeReportByAccommodation_Result> SP_RoomTypeReportByAccommodation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RoomTypeReportByAccommodation_Result>("SP_RoomTypeReportByAccommodation");
        }
    
        public virtual ObjectResult<SP_RoomTypeReportByBooking_Result> SP_RoomTypeReportByBooking()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RoomTypeReportByBooking_Result>("SP_RoomTypeReportByBooking");
        }
    
        public virtual ObjectResult<SP_RoomTypeReportByDeparted_Result> SP_RoomTypeReportByDeparted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RoomTypeReportByDeparted_Result>("SP_RoomTypeReportByDeparted");
        }
    }
}
